chamber_of_deputies_reimbursement:
  query: "select distinct id, year, month, state, party, subquota_description, supplier, congressperson_name, total_net_value from chamber_of_deputies_reimbursement"
  metrics:
    - id:
        usage: "LABEL"
        description: "Reimbursement ID"
    - year: 
        usage: "LABEL"
        description: "Year that the reimbursement was made"
    - month:
        usage: "LABEL"
        description: "Month that the reimbursement was made"
    - state:
        usage: "LABEL"
        description: "Federal state that the reimbursement was made"
    - party:
        usage: "LABEL"
        description: "Party that the deputie is related to"
    - subquota_description:
        usage: "LABEL"
        description: "Subquota"
    - supplier:
        usage: "LABEL"
        description: "Company or person whom provided the receipt"
    - congressperson_name:
        usage: "LABEL"
        description: "Deputie who requested the reimbursement"
    - total_net_value:
        usage: "GAUGE"
        description: "Reimbursement value"

